# Generated by Django 3.1.7 on 2021-03-10 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_parametros'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Parametros',
            new_name='Parametro',
        ),
    ]
